Resources/config/mongodb.xml

It became broken after https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/d731443aa5ad7a12c133bd1d7b97fa242c546e1e commit

Fix ODM listener service arguments

---

Resources/doc/setup.md

*The Symfony Documenators started an initiative to make all bundle installation documentation consistent and  easy to understand for beginners. That'll improve the DX for starters using 3rd party bundles. The template can be found here: http://symfony.com/doc/current/cookbook/bundles/best_practices.html#installation-instructions*
I would like to ask you to use this template in your documentation.
If you have any comments on the template, please open an issue in the `symfony/symfony-docs` repository. Feedback will brings us to the ultimate template.

Applied standard installation template

---

Command/PopulateCommand.php

getProgress() is not available and getStep() throws a deprecation warning.

Additional change for 2.5 ProgressBar support

---

CHANGELOG-3.1.md
Index/MappingBuilder.php
Resources/doc/cookbook/custom-properties.md
Resources/doc/types.md
Tests/Functional/PropertyPathTest.php
Tests/Functional/TypeObj.php
Tests/Functional/app/ORM/config.yml
Tests/Transformer/ModelToElasticaAutoTransformerTest.php
Transformer/ModelToElasticaAutoTransformer.php

Permits specific properties to define different property paths from their index field names.
This also allows for dynamic properties by setting the property_path to false, which will skip transformation of that property.

Added capability to define property paths

---

Resources/doc/usage.md

The example for the Knp Paginator was missing in the usage documentation.

Add missing KnpPaginator example in the usage documentation

---

Provider/AbstractProvider.php

Uses the deprecated interface for setting allowed types

Fix symfony 2.3 compatibility with 3.1

---

Resources/doc/setup.md

The parameter %kernel.env% does not exist. It throws the error message 'You have requested a non-existent parameter "kernel.env". Did you mean this: "kernel.environment"?'

Fixed parameter name to kernel.environment

---

Paginator/RawPaginatorAdapter.php

You don't have to execute the entire query to just count the number of result.

Count the number of results for the query directly

---

Resources/doc/cookbook/aliased-indexes.md
Resources/doc/cookbook/custom-repositories.md
Resources/doc/cookbook/manual-provider.md
Resources/doc/serializer.md
Resources/doc/types.md
Resources/doc/usage.md

I found it confusing that there are different index names used
throughout the documentation. I think using the index name "app"
consistently everywhere makes the docs easier to understand.

[DX] Use consistent index name in documentation

---

Doctrine/AbstractProvider.php
Propel/Provider.php

This avoids increasing the max of the progress bar to the upper multiplier of the batch size.
@XWB @merk I made this change based on the master branch, as I suggest we stop maintaining 3 parallel branches of the bundle (3.0, 3.1 and master). We should try to maintain only the master branch (until we start working on the next major version in which case we will need a 3.x branch). This will simplify the bundle maintenance.

Fix the progress logging for the last incomplete slice

---

Tests/Transformer/ModelToElasticaAutoTransformerTest.php
Transformer/ModelToElasticaAutoTransformer.php

This fixes #357 for the 3.0.x branch.
See https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/918 for the PR to the 3.1.x branch.

Don't use parent identifier for objects/nested documents (3.0.x branch)

---

DependencyInjection/Configuration.php
DependencyInjection/FOSElasticaExtension.php
Tests/DependencyInjection/FOSElasticaExtensionTest.php
Tests/DependencyInjection/fixtures/driverless_type.yml

This change allows the definition of a type with its own custom persister implementation without needing to define a driver type.

Allow driverless types

---

Propel/ElasticaToModelTransformer.php

The ElasticaToModelTransformer failed when fetching propel results. This is solved by converting the PropelCollection returned by `->find()` into an array.

Fixed PropelCollection to array casting error

---

DataCollector/ElasticaDataCollector.php
Elastica/Client.php
Logger/ElasticaLogger.php
Resources/views/Collector/elastica.html.twig

The only time showed by this bundle is the whole time taken by the request : latency + query + fetch. So a fast query but a long fetch is marked as slow in the debug toolbar. 
With this patch I want to address this case : 
- query 1: 100ms executionTime 
- query 2 : 20ms executionTime
Naturally I want to optimize query 1, but with more analysis, what happened is that : 
- query 1: 100ms executionTime, 1ms queryTime
- query 2 : 20ms executionTime, 15ms queryTime
So the fix is different : I need to work on the query itself on query 2 and on the data retrieved on query 1.
I also return the number of result given by the query, as it can give a useful info about the query (hello the sort on 1000000 results, better shrink the resultset).
This is a very naive approach and we sure can add more …

Differentiate query time from execution time

---

CHANGELOG-3.2.md
Configuration/TypeConfig.php
DependencyInjection/Configuration.php
DependencyInjection/FOSElasticaExtension.php
Index/MappingBuilder.php
Resources/doc/types.md
Tests/Functional/MappingToElasticaTest.php
Tests/Functional/app/Basic/config.yml

This PR add support for the `dynamic` option in mapping.
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html
This option allow to control when Elasticsearch is allowed to dynamically map an unknown field. I added as an example what is known to be a good practice, which is disabling the dynamic mapping completely, and then allowing it for some particular fields.

Add dynamic option in mapping at the type and field level

---

Paginator/RawPaginatorAdapter.php

The current RawPaginatorAdapter uses the getFacets method. This method is not available in newer versions of rufin/elastica.

Added method check for getFacets for RawPaginatorAdapter to support newer versions of rufin/elastica

---

Tests/Index/MappingBuilderTest.php

This fixes tests (and build) on PHP 5.3

Build fix: PHP 5.3 does not understand array short syntax

---

Index/Resetter.php
Tests/Index/ResetterTest.php

This should fix #853 when a user reset a specific type in an index and wants his changed settings (_analyzer_, _filters_, etc) to be taken into account.

Update settings when resetting a specific type

---

DependencyInjection/Configuration.php
DependencyInjection/FOSElasticaExtension.php
Resources/doc/serializer.md
Serializer/Callback.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/Functional/SerializerTest.php
Tests/Functional/app/Serializer/config.yml

It is currently impossible to populate attributes with a `null` value with FOSElasticaBundle, due to to the default behavior of JMS Serializer which doesn't serialize attributes with `null` values.
This PR adds an option to the `serializer` configuration so that the JMS Serializer can be configured with the `serialize_null` option.
There is no specific test for this PR, as it is a configuration for JMS Serializer, and I didn't find any other test concerning its configuration (for the `version` and `groups` options). I just updated the default test configuration (with a `false` value, which is the default value anyway), and added an example to the documentation for better clarity.

Allow serialize_null option for Serializer

---

Logger/ElasticaLogger.php
Resources/views/Collector/elastica.html.twig
Tests/Logger/ElasticaLoggerTest.php

Often there is needed to understand where ES query come from. This PR add backtrace information and show it in profiler. It is easy to find line, that raise query call:

Show query backtrace in profiler

---

Tests/Functional/ClientTest.php
Tests/Functional/app/Basic/config.yml
phpunit.xml.dist

This PR adds ability to overwrite default connection settings by customising `phpinit.xml` or by providing env variables, e.g.: 
```
$ export SYMFONY__FOS_ELASTICA__HOST=192.168.33.1
$ export SYMFONY__FOS_ELASTICA__PORT=19200
$ phpunit Tests/Functional/ClientTest.php
```

Allow to specify custom connection settings for functional tests

---

Subscriber/PaginateElasticaQuerySubscriber.php

Fallback to defaultSortFieldName and defaultSortDirection pagination options instead of ignoring then.

Made default sort options from pagination config to work as expected

---

Paginator/FantaPaginatorAdapter.php

Not having `PaginatorAdapterInterface` as one of `FantaPaginatorAdapter`'s interfaces kind of go against the purpose of having a `PaginatorAdapterInterface` in the first place...

Add PaginatorAdapterInterface as one of FantaPaginatorAdapter's interfaces

---

Resources/doc/cookbook/attachments.md

Greetings,
I was hoping to contribute some more documentation on handling attachments with the FOSElasticaBundle. It was difficult at first when I was dealing with attachments myself, and how to handle highlighting from the results. I think this will provide a better overview of how to handle attachments with elasticsearch and FOSElasticaBundle.
It was not until I saw this issue - https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/436, that I fully understood how to handle the HighlightableModelInterface.
Thank you for your time,
Aaron

Add Documentation for Mapping Attachments

---

Paginator/FantaPaginatorAdapter.php

As described in issue #1040 the PaginatorAdapterInterface should not be applied to the FantaPaginatorAdapter (which is the adapter for Pagerfanta).

[Bug Fix] Remove PaginatorAdapterInterface from Pagerfanta adapter

---

Doctrine/AbstractElasticaToModelTransformer.php

The original message doesn't actually help anybody. If this exception pops up provide the count of the Doctrine objects and the count of the Elastica results. Also print the IDs found by Elastica for further
investigation about the out-of-sync state.

Add More Debugging Output

---

CHANGELOG-3.2.md
DependencyInjection/Configuration.php
DependencyInjection/FOSElasticaExtension.php
Resources/doc/setup.md
Resources/doc/types.md

I've removed this option **immediate: true** from options of **listener**.
This option calls postFlush before any other doctrine event and avoids every update or insert of entity related to type of index.
i.e. If I declare that options such as
```
listener:
immediate: true
```
on my index this will not be synchronized with entities persisted on my database
P.S. I've removed it also from documentation.

Removed immediate option in config

---

Index/Resetter.php

when resetting index type and applying settings - parameter number_of_shards should be skipped, as it cannot be changed for existing index - elasticsearch would throw exception:
`ElasticsearchIllegalArgumentException[can't change the number of shards for an index]`
was introduced in #911

don't try to change number_of_shards on existing index

---

Resources/doc/cookbook/manual-provider.md

Fix to prevent the following exception while populating with manual provider:
> [Symfony\Component\Debug\Exception\ContextErrorException]
>  Warning: Missing argument 2 for FOS\ElasticaBundle\Command\ProgressClosureBuilder::FOS\Elastica
>  Bundle\Command\{closure}(), called in /vagrant/src/Acme/UserBundle/Provider/UserProvider.php on line 34 and defined
Trace:
> at /vagrant/vendor/friendsofsymfony/elastica-bundle/Command/ProgressClosureBuilder.php:39
> Symfony\Component\Debug\ErrorHandler->handleError() at /vagrant/vendor/friendsofsymfony/elastica-bundle/Command/ProgressClosureBuilder.php:39

Missing Parameters in $loggerClosure function in Manual Provider

---

DependencyInjection/FOSElasticaExtension.php

This will fix issue with `Mapping definition for [_parent] has unsupported parameters:  [identifier : id] [property : null]`

fixing issue with _parent mapping and ES 2.3.3

---

Subscriber/PaginateElasticaQuerySubscriber.php

Prevent error caused by ordering on empty fields

Allow ordering by unmapped fields

---

Doctrine/AbstractElasticaToModelTransformer.php
Tests/Transformer/ElasticaToModelTransformerCollectionTest.php
Transformer/AbstractElasticaToModelTransformer.php
Transformer/ElasticaToModelTransformerCollection.php

When using a lib such as `ramsey/uuid-doctrine` to handle object IDs, the cast is not performed blocking transformation.

Fixed ability to use an object as unique identifier

---

Configuration/TypeConfig.php
DependencyInjection/Configuration.php
DependencyInjection/FOSElasticaExtension.php
Index/MappingBuilder.php
Index/Resetter.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/fixtures/config.yml
Tests/Functional/MappingToElasticaTest.php
Tests/Functional/app/Basic/config.yml
Tests/Index/ResetterTest.php
composer.json

I've modified code to work with elasticsearch 2.3.1 with elastica 3.1.1. 
This breaks BC in order to comply with ruflin/elastica >= 3.1.
It's working for all the uses in our application with no queries' modification (however raises some deprecation notices)

WIP - Compatibility with elasticsearch 2

---

DependencyInjection/Configuration.php
Index/MappingBuilder.php
Tests/DependencyInjection/fixtures/config.yml
Tests/Functional/app/Basic/config.yml
Tests/Index/MappingBuilderTest.php

Fixes a bug introduced in #1069 
`identifier` and `property` fields were removed instead of just being deleted from mapping array before sending it to ES

Restore property and identifier in _parent node mapping

---

Doctrine/AbstractElasticaToModelTransformer.php

This is simply building on what was previously merged in PR #1067
This is doing the same, string-casting an object identifier, for a couple of cases which that PR did not cover.

Fixed ability to use object unique identifiers, continuing on 764ce12

---

DependencyInjection/FOSElasticaExtension.php
Doctrine/RepositoryManager.php
Manager/RepositoryManager.php
Manager/RepositoryManagerInterface.php
Resources/config/index.xml
Resources/config/orm.xml
Tests/Doctrine/RepositoryManagerTest.php
Tests/Functional/PersistenceRepositoryTest.php
Tests/Functional/TypeObject.php
Tests/Functional/TypeObjectRepository.php
Tests/Functional/app/ORM/config.yml
Tests/Manager/RepositoryManagerTest.php

i've ported the repositoryManager refactoring from our fork as requested in https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1069#issuecomment-238535208
As stated in the original PR:
Currently there is no way to create more than one type associated with a model, each with its own repository class.
This PR adds this possibility, refactoring the RepositoryManager class
Now a repository can be retrieved through the `fos_elastica.repository_manager` service calling getRepository method with `index/type` string as first argument.
Old doctrine repository manager class has been deprecated, but are still working as expected.
BC breaks are present ONLY if the doctrine repository manager has been extended, while usage remains the same

Repository Manager refactoring

---

Command/PopulateCommand.php

Accidentally discovered annoying bug.  
We have "large" dev-index (~12Gb ~6 millions docs) and when we need to update N documents we use `--no-reset` with `--type`, but today when running update `--type` wasn't added and `PopulateCommand` delete current index. :(
Fix: do not `postPopulate`, if `--no-reset` is passed.

[BUG] using --no-reset without --type

---

Doctrine/AbstractProvider.php
Doctrine/ORM/Provider.php

This adds a possibility to not only specify a method that creates a query builder, but also to supply extra parameters for the method call.
The previous implementation didn't really allow much flexibility when creating a query builder; just having a single method called at all times for a given type is a constraint that has limited several use cases for me, and I think I might be not the only one having this kind of trouble.
Note: this is in an un-tested state, I should fix this.

Allow passing extra parameters to queryBuilder factory

---

Doctrine/MongoDB/Provider.php

After pull  #1007  , i found next error:
`Fatal error: Declaration of FOS\ElasticaBundle\Doctrine\MongoDB\Provider::createQueryBuilder() must be compatible with FOS\ElasticaBundle\Doctrine\AbstractProvider::createQueryBuilder($method, array $arguments = Array)      `
Added "Allow passing extra parameters to queryBuilder factory" to MongoDB

Fix for MongoDB

---

Provider/AbstractProvider.php

When using `\FOS\ElasticaBundle\Provider\AbstractProvider` (Doctrine ORM)
```
[Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException]
The options "reset" do not exist. Defined options are: "batch_size", "clear_object_manager", "debug_logging", "igno
re_errors", "indexName", "offset", "query_builder_method", "skip_indexable_check", "sleep", "typeName".
```

[BUG] UndefinedOptionsException: The options "reset" do not exist.

---

Command/PopulateCommand.php

Automatic index switch doesn't work due to this commit
[fixing bug with using --no-reset without --type](https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/5bbee65058946e7124586699478982ff0304bd85)
Fixes #1140

Call postPopulate with reset option

---

DataCollector/ElasticaDataCollector.php
Elastica/Client.php
Logger/ElasticaLogger.php
Resources/views/Collector/elastica.html.twig
Tests/Elastica/ClientTest.php
Tests/Logger/ElasticaLoggerTest.php

I've noticed that execution time in profiler is wrong:
- Removed `$start` and `$end` from overridden `Client` in favor of `getQueryTime`
- Code Style fixes and improved type hinting in `logQuery`
- Cleaned `ElasticaLogger` by extending `AbstractLogger` which already implemented all methods required by interface
Before:
After:

Execution time in profiler is not accurate 

---

Resources/doc/cookbook/custom-repositories.md

Removed by documentation reference to annotation `@Search` to declare a custom repository,
In ref. to PR #1119 .

Removed search annotation from documentation

---

Index/Resetter.php

We have `PRE_INDEX_RESET` event, which is triggered before creating a new index, but currently it's not aware of "real" index name because it's called before `AliasProcessor::setRootName`.
In this PR I just moved PRE_INDEX_RESET dispatch after `AliasProcessor::setRootName` is called.

PRE_INDEX_RESET should be aware about originalName

---

Resources/config/mongodb.xml

I get this exception with symfony2 using doctrine and mongodb:
`Fatal Error: Argument 2 passed to FOS\ElasticaBundle\Doctrine\RepositoryManager::__construct() must implement interface FOS\ElasticaBundle\Manager\RepositoryManagerInterface, instance of Doctrine\Common\Annotations\CachedReader given`
I don't know if this issue needs more code but it seems to work.

Fix MongoDB config

---

Index/Resetter.php

In version 1 of ES, the settings are different. Also the number_of_replicas cannot be changed on closed indexed as well:
> Can't update [index.number_of_replicas] on closed indices [] - can leave index in an unopenable state

Fix resetIndexType on ES 1.x

---

Resources/doc/usage.md
Subscriber/PaginateElasticaQuerySubscriber.php
Tests/Subscriber/PaginateElasticaQuerySubscriberTest.php

Should resolve #1159
Added support for `sortNestedPath` and `sortNestedFilter` options to knp paginator `paginate` method.
Allows to specify `nested_path` and `nested_filter` sort fields when paginating, passing a string or a callable accepting the current sort field.

Support nested_path and nested_filter sort attributes when using knp pager

---

Command/PopulateCommand.php
Command/ProgressClosureBuilder.php

This fixes the  #914 issue. ProgressBar now starts at the position of the specified offset. I was also considering if it should start at 0 with max value decreased by offset value.

Fixed PopulateCommand when --offset has been specified

---

Command/PopulateCommand.php

QuestionHelper has no method askConfirmation(), use ask()
Problem is caused by migration from DialogHelper to QuestionHelper in this commit: https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/9824b56143f448979430f764508dddb4231e072e

Fix call of unknown method QuestionHelper::askConfirmation()

---

Index/Resetter.php

Settings variable is not defined before condition. ```!empty($settings)``` will always return ```false``` which cause this code be never executed.

Remove never executed code from Resetter

---

Doctrine/Listener.php

Hi,
I use FOSElastica in DDD symfony project. In this project identifiers of root aggregates are implemented as Value Object. For example this is UserId (Identifier of User entity): https://gist.github.com/szepczynski/306c2e3bc793b679a7cb3c8a89abaa7e
I create mapping, add some functionality and write some tests. In test I got few errors related with identifier.
I started with this mapping: 
https://gist.github.com/szepczynski/78a4d700bb06f50fdc3b59623d1f9329
and got error: Elastica\Exception\ResponseException: Malformed action/metadata line [1], expected a simple value for field [_id] but found [START_OBJECT]
I change the identifier to id.value but this change make error when bundle trying to get results from doctrine repository:
```
[Semantical Error] line 0, col 50 near 'value IN(:va': …
```

Fix deleting objects with identifier as object value

---

DependencyInjection/Configuration.php
DependencyInjection/FOSElasticaExtension.php
Doctrine/Listener.php
Resources/doc/types.md
Tests/Doctrine/AbstractListenerTest.php

Added a new configuration option that defers Doctrine caused updates until after `kernel.terminate`. Useful for when fast response times are important.

Support for asynchronous persistence

---

Command/PopulateCommand.php
DependencyInjection/FOSElasticaExtension.php
Event/IndexPopulateEvent.php
EventListener/PopulateListener.php
Index/AliasProcessor.php
Index/Resetter.php
Resources/config/event_listener.xml
Tests/Index/ResetterTest.php

In case if you don't want to delete old index (backup for emergency case) you should close it.
Adding `--no-delete` option to `PopulateCommand`

Ability to close index instead of delete

---

CHANGELOG-4.0.md
Finder/TransformedFinder.php
Tests/Finder/TransformedFinderTest.php

`Elastica\Type::moreLikeThis` doesn't exist anymore.

Removed TransformedFinder::moreLikeThis

---

DependencyInjection/Configuration.php

This snippet disables normalization (replacing - to _) for headers, for example "Content-Header" is named as "Content_Header"

Disable normalize keys for headers

---

Propel/ElasticaToModelTransformer.php

I've restored use of sortingClousure at Transformer because returned results always had random order.

[Propel] Restored proper object sorting

---

.travis.yml

Since elasticsearch is not available in trusty distro (https://docs.travis-ci.com/user/trusty-ci-environment#Data-Stores) it should not be referenced in the config at all as it is useless anyhow

remove elasticsearch service from travis.yml

---

DependencyInjection/FOSElasticaExtension.php
Doctrine/Listener.php
Resources/doc/types.md
Tests/Doctrine/AbstractListenerTest.php

This PR improves https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/878, by also subscribing to the `console.terminate` event, in order to handle entities persisted in CLI commands.

Subscribe to console.terminate event when defer is true

---

Command/CreateCommand.php
Tests/Command/CreateCommandTest.php

Right now it's impossible to create empty index with mapping without hacking things.
This PR will implement `fos:elastica:create` command for this purposes.

Create index command

---

DependencyInjection/Configuration.php
Tests/DependencyInjection/ConfigurationTest.php

When trying to set up the `AwsAuthV4` transport to use port 443 I found this block of code in the underlying Elastica class:
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/AwsAuthV4.php#L77
I couldn't find anywhere to be able to define the `ssl` config that it was looking for, this PR adds that to a connection in the same way all of the AWS_* config is set.
If it's just a case of me missing where to set up this config, please point me in the right direction :D

Added an ssl key to the DependecyInjection config

---

Resources/config/config.xml
Resources/views/Collector/elastica.html.twig

Hi,
This is a PR to make compatible with Symfony 3.3 the call of twig templates.
Without this PR, web debug toolbar throw this exception : "The profiler template "FOSElasticaBundle:Collector:elastica.html.twig" for data collector "elastica" does not exist."

Fix call to twig templates with Symfony 3.3

---

Command/PopulateCommand.php
Persister/Event/Events.php
Persister/Event/PostAsyncInsertObjectsEvent.php
Tests/Persister/Event/PostAsyncInsertObjectsEventTest.php

The event should be used by async pager persisters that do not fetch objects itself but delegate it to some workers or so.

add post async insert objects event

---

CHANGELOG-4.0.md
Doctrine/Listener.php
Tests/Transformer/ModelToElasticaAutoTransformerTest.php
Transformer/ModelToElasticaAutoTransformer.php

Rebased #1327 against 4.x. Will then merge 4.x into master.
When we add scalar type declarations in the future, this is what would happen implicitly anyway.
And it is concistent with #1067

Cast identifier to string

---

.travis.yml
doc/setup.md

- types and indexes difference is removed with ES 6
- also disable xdebug when not using coverage

remove outdated elasticsearch doc

---

doc/setup.md

AFAIR console file is placed in bin folder since Symfony 3. Just a small fix.

[Documentation] Proper symfony console path

---

composer.json

Small fix to be more consistent with semantic versioning. We cannot be 100% sure, that this bundle will work with php 8

Change minimum php version

---

src/DependencyInjection/Compiler/RegisterPagerPersistersPass.php
src/DependencyInjection/Compiler/RegisterPagerProvidersPass.php
src/DependencyInjection/Compiler/RegisterPersistersPass.php
src/FOSElasticaBundle.php

Waiting until the before_removing step to check for persisters breaks support for service decoration, as it has already been resolved at this point (and so the original id won't be used anymore to reference the service).
The only benefit was that the class was already resolved in case a parameter was used, but this is solved in a better way by resolving the value.
Note that decorating object persisters was working totally fine in version 3.x of the bundle (and yes, I have a project which is just migrating away from ES 1.7 now).

Fix support for decorating persister services

---

src/DependencyInjection/FOSElasticaExtension.php

The extending client provided by the bundle to add extra logging should not be enforced for typehints. It creates extra coupling to the bundle. The typehint should rather be on the library class.

Add autowiring support for Elastica\Client

---

doc/usage.md

I had a hard time finding out exactly where and how to pass ES query parameters - in my case, I needed to have `?search_type=dfs_query_then_fetch` added to the ES HTTP call, but couldn't find any hints in the docs.
I have added a paragraph to the usage chapter which should point people into the right direction.

Added usage documentation on how to pass general ES query parameters.

---

src/Command/ProgressClosureBuilder.php
src/Configuration/ConfigManager.php
src/Configuration/ManagerInterface.php
src/Configuration/Source/ContainerSource.php
src/Configuration/Source/SourceInterface.php
src/Configuration/TypeConfig.php
src/DependencyInjection/Compiler/ConfigSourcePass.php
src/DependencyInjection/Compiler/IndexPass.php
src/Event/IndexEvent.php
src/Event/IndexPopulateEvent.php
src/Event/IndexResetEvent.php
src/Event/TransformEvent.php
src/Event/TypePopulateEvent.php
src/Event/TypeResetEvent.php
src/Index/AliasProcessor.php
src/Index/MappingBuilder.php
src/Provider/Indexable.php
src/Provider/IndexableInterface.php
src/Transformer/AbstractElasticaToModelTransformer.php

All files have the right header (and PHP-CS-Fixer is configured to enforce it). But a bundle of files were holding a second header after it.

Remove bad duplicate license headers

---

src/Doctrine/ORMPagerProvider.php
tests/Unit/Doctrine/ORMPagerProviderTest.php

Paginating a DQL query which does not have a ORDER BY clause does not work cross-platform, as the sorting is undefined in such case.
MySQL is not affected by the bug because it always adds an implicit sorting by insertion order (which is a compliant way to implement the undefined order but tends to hide this issue from developers having to deal with other platforms too). But PostgreSQL is impacted for instance.

Fix pagination of ORM queries when populating

---

composer.json
src/Persister/ObjectPersister.php
src/Persister/ObjectPersisterInterface.php

Fixes https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1268
Closes https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1428

Add optional routing to ObjectPersister::deleteById

---

src/Transformer/AbstractElasticaToModelTransformer.php
tests/Unit/Transformer/AbstractElasticaToModelTransformerTest.php
tests/Unit/UnitTestHelper.php

Remove getSortingClosure, as it is not used anywhere
Introduce a UnitTestHelper class for some shared functionality

Testing AbstractElasticaToModelTransformer

---

src/Persister/ObjectPersister.php

Original bug introduced by 6d079107d40e3c195fc44774edc749143dfd40bb
Well not "introduced" but that commit supposedly provided this enhancement but didn't actually

Fixes: ObjectPersister not passing $routing to deleteManyByIdentifiers

---

src/Doctrine/AbstractElasticaToModelTransformer.php
tests/Unit/Doctrine/AbstractElasticaToModelTransformerTest.php

Display ids of missing objects in exception message when `ignore_missing` option is used.

Add missing ids in exception message

---

doc/cookbook/aliased-indexes.md

missing content type to req else error 406 `{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}`

[documentation] missing content type to req

---

doc/cookbook/aliased-indexes.md

change orders actions to avoid downtime and add some usefull informations

[documentation]  Be a little bit verbose with aliases and setup

---

doc/cookbook/speed-up-populate-command.md

There is no recipe to create "enqueue_elastica" config. Without this config script is crushing with error "The child node "transport" at path "enqueue_elastica" must be configured."

missed default config section

---

.gitignore
src/DependencyInjection/FOSElasticaExtension.php

I tried to use the `7.0.x-dev` branch in our Symfony project to add support for Elasticsearch 7, by adding the following the our composer.json:
```
"ruflin/elastica": "7.0.x-dev as 6.1.1",
```
Unfortunately this triggered the following errors:
```
Argument 3 passed to Elastica\\Connection\\ConnectionPool::__construct() must be callable or null, string given, called in \/var\/www\/html\/vendor\/ruflin\/elastica\/lib\/Elastica\/Client.php on line 148","detail":"Argument 3 passed to Elastica\\Connection\\ConnectionPool::__construct() must be callable or null, string given, called in \/var\/www\/html\/vendor\/ruflin\/elastica\/lib\/Elastica\/Client.php on line 148 in \/var\/www\/html\/vendor\/ruflin\/elastica\/lib\/Elastica\/Connection\/ConnectionPool.php at 38","source":{"trace":"#0 …
```

Add support for Elastica 7.0.x-dev

---

src/Subscriber/PaginateElasticaQuerySubscriber.php
tests/Unit/Subscriber/PaginateElasticaQuerySubscriberTest.php

Fix #1202 
PaginateElasticaQuerySubscriber depending on RequestStack but there is no check if the stack is empty or not on usage. When using pagination from console, the stack is empty.
Add a default null when request stack is empty.

Fix paginate subscriber when request stack is empty (eg. console).

---

src/Subscriber/PaginateElasticaQuerySubscriber.php

This will fix:
```
FOS\ElasticaBundle\Tests\Unit\Subscriber\PaginateElasticaQuerySubscriberTest::testShouldDoNothingIfSortParamIsEmpty
TypeError: Argument 1 passed to Symfony\Component\HttpFoundation\Request::get() must be of the type string, null given, called in ./FOSElasticaBundle/src/Subscriber/PaginateElasticaQuerySubscriber.php on line 153
```

Fix PaginateElasticaQuerySubscriberTest

---

src/Command/CreateCommand.php
src/Command/PopulateCommand.php
src/Command/ResetCommand.php
src/Command/SearchCommand.php

Non-int status codes in Command::execute() are deprecated since Symfony 4.4:
- https://github.com/symfony/symfony/issues/33747
- https://github.com/symfony/symfony/pull/33775

Add return codes to commands to fix deprecated null return values

---

src/Repository.php

phpstan error :
`Parameter #1 $query of method FOS\ElasticaBundle\Repository::createPaginatorAdapter() expects string,  Elastica\Query given.`
In the interface `FOS\ElasticaBundle\Finder\PaginatedFinderInterface`, the method `createPaginatorAdapter` accepts `* @param mixed $query` but in `FOS\ElasticaBundle\Repository`, this method accepts only `* @param string $query`.
The next block of code is correct but in phpstan, it throws an error because of parameter type in Repository
```
/** @var Elastica\Query $query */
$query = $this->getQueryFromData($requestQuery, $user);
$count = $this->createPaginatorAdapter($query)->getTotalHits();
```
So I suggest to change the PHPDoc of this method which will keep the same behavior :+1:

Fix phpstan warnings in projects

---

tests/Functional/app/ORM/config.yml
tests/Functional/app/Serializer/config.yml

Use the Elasticsearch host and port parameters in all tests instead of the default localhost:9200.

Use Elasticsearch host and port parameters in all tests

---

src/Command/CreateCommand.php
tests/Unit/Command/CreateCommandTest.php

I have configured aliases for my indexes with `use_alias: true` and wanted to use . `./bin/console fos:elastica:create` to create them. 
I expected the command to create the index and adding the configured alias, but it only created the indexes. So here is a fix for that.

Add alias to index on index creation

---

src/Finder/PaginatedFinderInterface.php
src/Finder/TransformedFinder.php

stof : the only BC break in it currently (making it a 6.x-dev) is the findHybridPaginated method in PaginatedFinderInterface. This could be added first as a @method in 5.x (as Symfony does)

Reverted bc break

---

composer.json

Elasticsearch 7 and corresponding `ruflin/elastica` library will only be available in next major version.

Removed support for Elasticsearch 7

---

composer.json
src/Doctrine/AbstractElasticaToModelTransformer.php
src/Doctrine/Listener.php
src/Doctrine/MongoDBPagerProvider.php
src/Doctrine/ORMPagerProvider.php
src/Doctrine/PHPCRPagerProvider.php
src/Doctrine/RegisterListenersService.php
src/Doctrine/RepositoryManager.php
tests/Unit/Doctrine/AbstractElasticaToModelTransformerTest.php
tests/Unit/Doctrine/ORM/ElasticaToModelTransformerTest.php
tests/Unit/Doctrine/PHPCR/ElasticaToModelTransformerTest.php
tests/Unit/Doctrine/PHPCR/ListenerTest.php
tests/Unit/Doctrine/PHPCRPagerProviderTest.php
tests/Unit/Doctrine/RegisterListenersServiceTest.php
tests/Unit/Doctrine/RepositoryManagerTest.php

A backwards-compatibility layer has been added to persistence to help
consumers move to the new namespacing. It is based on class aliases,
which means the type declaration changes should not be a BC-break: types
are the same.
See doctrine/persistence#71
This means:
- using the new namespaces
- adding autoload calls for new types to types that may be extended and
use persistence types in type declarations of non-constructor methods,
so that signature compatibility is recognized by old versions of php.
More details on this at
https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf

Address deprecations from persistence

---

src/Finder/TransformedFinder.php
tests/Unit/Finder/TransformedFinderTest.php

A simple method allowing the ease of use of Finder, and avoiding database calls when entities are not required.

Add finder method to retrieve raw ElasticSearch documents

---

.travis.yml

Run tests on Symfony 4.4 avoiding to use a bad version (like symfony/stopwatch 3.4 with prefer-lowest option)

Run tests on both symfony versions supported

---

src/DependencyInjection/FOSElasticaExtension.php

With this PR you should be able to automatically get the right service injected when using the good type-hint and client name suffixed with `client`

Add autowiring alias for named clients

---

doc/usage.md

Adding a small note about different behavior of ES 7.6 and 7.7 , closes #1727

updating docs, adding hint for adding multiple queries to bool

---

src/DependencyInjection/Compiler/RegisterPagerProvidersPass.php
src/DependencyInjection/FOSElasticaExtension.php
tests/Unit/DependencyInjection/Compiler/RegisterPagerPersistersPassTest.php
tests/Unit/DependencyInjection/Compiler/RegisterPagerProvidersPassTest.php
tests/Unit/DependencyInjection/Compiler/RegisterPersistersPassTest.php

Symfony 5.2 removed the `setPrivate(false)` call from the `ChildDefinition` class (https://github.com/symfony/dependency-injection/commit/93123c0f564828ee0df027fbf98ad0b084f0966d#diff-053e10444fda1f5cfb6c16eee77d265e49962ec674d505e036a7238b78af8eb4), causing this bundle to throw exception on own registered services during its compiler passes. 
I know that with version 6 of this bundle most services are marked as private, but for the people not wanting to upgrade to v6 (yet), this can be a small service release of the 5.2 version.

Explicitly mark public services as public for Symfony 5.2 compatibility

---

src/Event/PostIndexMappingBuildEvent.php
src/Event/PostMappingBuildEvent.php
src/Index/MappingBuilder.php

This would allow to easily check if event needs to be handled for a specific index, by using for example:
```php
if ('my_index' === $event->getIndex()) {
// do stuff
}
```

Make PostMappingBuildEvent extends IndexEvent

---

src/Command/CreateCommand.php

This is complementary to https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1577
Permit to disable automatic aliasing when creating a new index.
This is useful when creating a new index that will be switched later (once populate is done for example).

Allow to disable aliasing when creating index

---

.travis.yml

Test on PHP 8.0

---

.github/workflows/continuous-integration.yaml
CHANGELOG-6.0.md
composer.json
src/Doctrine/MongoDBPagerProvider.php
src/Doctrine/ORMPagerProvider.php
src/Doctrine/PHPCRPagerProvider.php
src/Paginator/FantaPaginatorAdapter.php
tests/Unit/Doctrine/MongoDBPagerProviderTest.php
tests/Unit/Doctrine/ORMPagerProviderTest.php
tests/Unit/Doctrine/PHPCRPagerProviderTest.php

This follows #1764 in order to support version 2.x and 3.x of pagerfanta.
This allows to still be compatible with PHP versions anterior to 7.4

Support pagerfanta 2.x and 3.x

---

src/Resources/config/config.xml

Supersedes https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1750
Closes #1737
```
User Deprecated: Since symfony/property-access 5.2: Passing a boolean as the first argument to "Symfony\Component\PropertyAccess\PropertyAccessor::__construct()" is deprecated. Pass a combination of bitwise flags instead (i.e an integer).
```
PR changes `false`  to `0`
From https://github.com/symfony/property-access/blob/5.x/PropertyAccessor.php#L94
```php
$magicMethods = ($magicMethods ? self::MAGIC_CALL : 0) | self::MAGIC_GET | self::MAGIC_SET;
```

fix symfony/property-access magicCall deprecation

---

src/Doctrine/AbstractElasticaToModelTransformer.php

Since PHP 8 returning `bool` from `usort` callback function is deprecated. This small change migrates to using spaceship operator, which is available since PHP 7.0.

Use spaceship operator within usort callback

---

composer.json
src/Resources/config/config.xml

Since Symfony 5.3 is deprecated to construct PropertyAccessor with a `bool` value as second argument.
Ref: https://github.com/symfony/property-access/blob/8988399a556cffb0fba9bb3603f8d1ba4543eceb/CHANGELOG.md#530

Fix deprecation with Symfony 5.3

---

composer.json
src/Command/CreateCommand.php
src/Command/DeleteCommand.php
src/Command/PopulateCommand.php
src/Command/ResetCommand.php
src/Command/ResetTemplatesCommand.php
src/Command/SearchCommand.php
src/DataCollector/ElasticaDataCollector.php

This PR normalizes `composer.json` and adds phpdoc return types to avoid deprecation warnings using Symfony 5.4

Remove deprecations using Symfony 5.4

---

doc/cookbook/populate-events.md

forcemerge takes arguments in query parameters, not in the request body

---

src/Persister/AsyncPagerPersister.php

I was getting this error with the latest version of Doctrine ODM Bundle:
```
(TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, Doctrine\\ODM\\MongoDB\\Iterator\\CachingIterator given at /app/vendor/friendsofsymfony/elastica-bundle/src/Persister/AsyncPagerPersister.php:90)"}
```
so this fixes that issue to be able to count a Traversable as well

fix: result count for Traversable

---

src/Transformer/ModelToElasticaAutoTransformer.php
tests/Unit/Transformer/ModelToElasticaAutoTransformerTest.php

Hello, I don't know if this is a real problem or only my problem.
In fact, looking at the pieces of code below, the first is the current result and the second is the expected result and that I would rather have.
```php
{
"childOf": [],
"section": {
"label": "section"
},
"nature": {
"label": "nature"
}
}
```
```php
{
"childOf": null,
"section": {
"label": "section"
},
"nature": {
"label": "nature"
}
}
```
In my fos_elastica.yaml, my "childOf" property is declared as an object.
```yml
app_company:
properties:
childOf:
type: object
properties:
id: ~
```
Except that I find that it is not very logical to recover an empty array instead of null for an object whose value is null in database.
What do you think of my proposition ?
Thanks

Return null instead of [] for a null object in Elastica Document

---

.github/workflows/continuous-integration.yaml
README.md
composer.json
src/Logger/ElasticaLogger.php
src/Subscriber/PaginateElasticaQuerySubscriber.php
tests/Functional/ClientTest.php
tests/Functional/ConfigurationManagerTest.php
tests/Functional/IndexTemplatesTest.php
tests/Functional/IndexableCallbackTest.php
tests/Functional/MappingToElasticaTest.php
tests/Functional/PersistenceRepositoryTest.php
tests/Functional/PropertyPathTest.php
tests/Functional/ResetTemplatesCommandTest.php
tests/Functional/SerializerTest.php
tests/Functional/WebTestCase.php
tests/Functional/app/AppKernel.php
tests/Unit/Doctrine/AbstractListenerTest.php
tests/Unit/Doctrine/MongoDB/ListenerTest.php
tests/Unit/Doctrine/ORM/ListenerTest.php
tests/Unit/Doctrine/PHPCR/ListenerTest.php

supersedes https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1840
This PR adds a CI job to test with Symfony 6, ~the `ConfigSourcePassTest` has been changed because there was a problem with `replaceArgument` not returning anything and I decided to change it to use an actual `ContainerBuilder`.~ (solved in https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1845)

Allow Symfony 6

---

.github/workflows/continuous-integration.yaml
composer.json

We implement it in https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/723c6649efadcbf3331daa91e4c5a6e89288d904/src/Logger/ElasticaLogger.php which [is already compatibly with version 2 and 3](https://github.com/php-fig/log/compare/2.0.0...3.0.0).
psr/log 3 cannot be installed because [`elasticsearch-php` doesn't support it yet](https://github.com/elastic/elasticsearch-php/blob/d7539aa7c414a92ee34ae95070da1bc5dd9d30c3/composer.json#L19).
I've also modified the job matrix to add more tests with different versions.

Allow install psr/log 2 and 3

---

composer.json

these bundles are not used, only the integrating packages

Remove unused bundles

---

src/Command/CreateCommand.php
src/Command/DeleteCommand.php
src/Command/PopulateCommand.php
src/Command/ResetCommand.php
src/Command/ResetTemplatesCommand.php
src/Command/SearchCommand.php
src/Resources/config/commands.xml

This will keep [the command lazy loaded](https://symfony.com/doc/4.4/console/commands_as_services.html#lazy-loading) and prevents triggering deprecations when using [Symfony 6.1](https://github.com/symfony/symfony/blob/6.1/UPGRADE-6.1.md#console)

Move command name to tag attribute

---

.github/workflows/continuous-integration.yaml

This will allow using modern PHP features, e.g. for Enums in https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1866
PHP 8.1 support was introduced in php-cs-fixer v3.4.0, but I decided to update it to the latest version available.

Run code style checks on PHP 8.1

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/FOSElasticaExtension.php

Fixes #1596 
This adds support for the `aws_credential_provider` setting in Elastica, which was added in https://github.com/ruflin/Elastica/pull/1667
Example usage:
```yaml
// config/packages/fos_elastica.yaml
fos_elastica:
clients:
default:
host: '%env(ELASTICSEARCH_HOST)%'
port: '%env(ELASTICSEARCH_PORT)%'
transport: "AwsAuthV4"
aws_region: "eu-central-1"
aws_credential_provider: 'aws.credentials_provider'
services:
Aws\Credentials\CredentialProvider:
aws.credentials_provider:
class: 'Aws\Credentials\CredentialProvider'
factory: [ '@Aws\Credentials\CredentialProvider', 'defaultProvider' ]
```

Add support for 'aws_credential_provider'

---

src/Resources/views/Collector/elastica.html.twig

Reasoning: it's very hard to read the log if there are some non-ascii chars in it.

Don't escape unicode in the query log

---

src/HybridResult.php

This allows users to annotate what transformed object is contained in their HybridResults by annotating their search repositories.
See https://phpstan.org/blog/generics-in-php-using-phpdocs for more information about generics.

Add PHPStan template to HybridResult

---

doc/indexes.md

The dynamic_templates expects an array. That's nice, we the example states differently. I was only able to came up to the solution because of the issue below, but no action was done because of that 😢 
https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1849

[docs]Update Dynamic Templates documentation based on issue

---

src/Finder/HybridFinderInterface.php
src/Finder/PaginatedHybridFinderInterface.php
src/Finder/PaginatedRawFinderInterface.php
src/Finder/RawFinderInterface.php
src/Finder/TransformedFinder.php

Previously, `TransformedFinder`'s public methods were poorly covered with interfaces. This PR adds missing, granular contracts for each public method.
✅ Each public method of `TransformedFinder` is covered by interface
✅ Each interface is granular
✅ Backward-compatible
I wanted to clean up the `PaginatedFinderInterface`, but due to BC reasons I decided to left it as is. Current state doesn't block making this PR working, and we can refactor it later, when new major would be on the horizon.

Add missing interfaces to TransformedFinder

---

composer.json

Instead of depending on the `pagerfanta/pagerfanta` monopackage (which installs everything), only the `pagerfanta/core` package needs to be a hard dependency.  The subsplit repos for the supported Doctrine integrations are already listed as dev requirements, so this mainly just lightens the production dependencies and allows Composer to work a bit more efficiently (the monorepo has a heavier list of conflicts to deal with because it's trying to set constraints for everything whereas the subsplit packages have rather small dependency lists).

Only require `pagerfanta/core`

---

src/Command/ConsoleProgressLogger.php
src/Command/PopulateCommand.php
src/Persister/Event/PostInsertObjectsEvent.php
src/Persister/Event/PreInsertObjectsEvent.php
src/Persister/InPlacePagerPersister.php
src/Persister/Listener/FilterObjectsListener.php

With the current populate command output you are not given insight in the amount of filtered objects, and they are not used to advance the progress bar as well. Before #1891 this would result in the progress bar not being completed at all, but now it jumps to the end as it is being marked as completed.
I propose the following adjustment: register the amount of filtered objects into the `PreInserObjectsEvent` and forward to the `PostInsertObjectsEvent`. There is also a `PostAsyncInsertObjectsEvent`, but I believe that is not being used at (~~will open a dedicated MR for it~~ #1893). With the data now available to the console logger, we can print the skipped/total object after the populating message, and adjust the progress bar total to show the amount of objects to be really inserted.
I …

Show filtered object count during populate

---

src/Persister/AsyncPagerPersister.php
tests/Unit/Persister/AsyncPagerPersisterTest.php

Async Persister is returning useless count that is not used anywhere but to calculate it, we are making an expensive COUNT() query.

Remove count from async persister

---

composer.json

This PR completes the tasks listed in #1938

Fix composer.json for doctrine/phpcr-odm:2.0

---

src/Elastica/Client.php

If an Elastica exception was thrown upon request, then make the request visible that caused it (on verbose console or in your logs), then rethrow the exception.
Example with corrupted request data on the console (calling `php bin/console --env=dev -vvv fos:elastica:populate` very verbose)
❓ 🤷🏻‍♂️ 
❗ 🕵🏻‍♂️

Client: log query on exception then rethrow it

---

composer.json
src/Serializer/Callback.php

To be consistent with the JMS Serializer configuration

Enable max depth for Symfony serializer too

---

composer.json
src/Doctrine/RegisterListenersService.php
tests/Unit/Doctrine/ORM/ElasticaToModelTransformerTest.php
tests/Unit/Doctrine/ORM/ListenerTest.php
tests/Unit/Doctrine/RegisterListenersServiceTest.php

Hi @XWB 
Closes https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1944

Add compatibility with doctrine/orm 3

---

doc/cookbook/populate-events.md

`optimize()` deprecated in favor of `forcemerge()` in Elastica v5.x and removed in v6.x.

optimize() deprecated and replaced with forcemerge()

---

doc/cookbook/speed-up-populate-command-sqs.md

- Update configuration in `enqueue.yaml`
- Update CLI instructions with new command behaviour
- Improve parameters declaration

[Docs] Update doc related to use of fos:elastica:populate command with SQS

---

src/DependencyInjection/FOSElasticaExtension.php

As per #1950 the `Symfony\Component\HttpKernel\DependencyInjection\Extension` is deprecated and `Symfony\Component\DependencyInjection\Extension\Extension` should be used.
This class is available in all Symfony versions supported by this bundle.

Use correct Extension class per Symfony deprecation

---

composer.json
src/Elastica/Client.php
src/Event/ElasticaRequestExceptionEvent.php
src/Event/PostElasticaRequestEvent.php
src/Event/PreElasticaRequestEvent.php
src/Resources/config/config.xml
tests/Unit/Elastica/ClientTest.php

Fixes #1963 
Things to consider: at this time it's not possible to pass the full request object in the `PreRequest` event as that object is created and used by the client below. It could be done if the library would change it so that it's in a separate method so we could override it.
The settting of `EventDispatcher` could also just be done in the constructor at this point.

Add events for requests

---

src/Doctrine/ConditionalUpdate.php
src/Doctrine/Listener.php
tests/Unit/Doctrine/AbstractListenerTestCase.php
tests/Unit/Doctrine/ConditionalUpdateEntity.php
tests/Unit/Doctrine/ConditionalUpdateListenerTest.php

It's a proposition for #1968.
Some tests are red but I think it's related to a dependency change.

Implement ConditionalUpdate interface for selective entity updates
