FriendsOfSymfony/FOSElasticaBundle

CHANGELOG-3.1.md, Event/TransformEvent.php, Resources/config/transformer.xml, Resources/doc/cookbook/custom-properties.md, Resources/doc/index.md, Tests/Transformer/ModelToElasticaAutoTransformerTest.php, Transformer/ModelToElasticaAutoTransformer.php
Added a new event that lets implementors of FOSElasticaBundle add custom indexed fields.
=> Dispatch an event when transforming objects

Resources/doc/setup.md
=> Clarified what index_name does. Closes #731

CHANGELOG-3.1.md, Command/PopulateCommand.php, Doctrine/AbstractProvider.php, Propel/Provider.php, Provider/AbstractProvider.php
Replaces #770
I did not implement ProgressHelper because it has too many problems to be easily implemented, if someone else wants to have a go they're welcome to attempt it.
=> Continued work on ProgressBar

CHANGELOG-3.1.md, Command/PopulateCommand.php, Command/ProgressClosureBuilder.php, Doctrine/AbstractProvider.php, Provider/ProviderInterface.php
Some general tidying of the ProgressCommand
=> Command tidy

CHANGELOG-3.1.md, Command/PopulateCommand.php, Doctrine/AbstractProvider.php, Doctrine/MongoDB/Provider.php, Doctrine/ORM/Provider.php, Doctrine/ORM/SliceFetcher.php, Exception/AliasIsIndexException.php, Index/AliasProcessor.php, Index/Resetter.php, Propel/Provider.php, Provider/AbstractProvider.php, Provider/Indexable.php, Resources/doc/types.md, Tests/Doctrine/AbstractProviderTest.php, Tests/Index/AliasProcessorTest.php, Tests/Index/ResetterTest.php, Tests/Provider/IndexableTest.php
Using this PR to watch coverage/issues with scrutinizer-ci
=> More test coverage

Resources/doc/cookbook/custom-properties.md
Updated cookbook with included service definition for provided listener class
=> Improve DX: added yaml service definition

Tests/Transformer/ModelToElasticaAutoTransformerTest.php, Transformer/ModelToElasticaAutoTransformer.php
=> Don't use parent identifier for objects/nested documents

DependencyInjection/Configuration.php, DependencyInjection/FOSElasticaExtension.php, Doctrine/PHPCR/ElasticaToDocumentTransformer.php, Doctrine/PHPCR/ElasticaToModelTransformer.php, Doctrine/PHPCR/Provider.php, Doctrine/PHPCR/SliceFetcher.php, Resources/config/phpcr.xml, Resources/doc/setup.md, Tests/Doctrine/PHPCR/ElasticaToModelTransformerTest.php, Tests/Doctrine/PHPCR/ListenerTest.php, composer.json
Follow https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/739
=> Adding PHPCR support

Resources/doc/types.md
The PR wants to update documentation in order to include new PHPCR driver supported.
As @dbu suggested, I just updated the `types` page.
=> Update types doc page

.travis.yml, composer.json
https://github.com/KnpLabs/KnpPaginatorBundle/pull/346 should be merged before
=> Allow this bundle to work with symfony3

Resources/doc/cookbook/custom-properties.md
Hi, 
just adding the two use statements in order to make the example work out of the box
=> add use namespace

CHANGELOG-3.2.md, Event/TransformEvent.php, Resources/doc/cookbook/pre-transform-event.md, Resources/doc/index.md, Tests/Transformer/ModelToElasticaAutoTransformerTest.php, Transformer/ModelToElasticaAutoTransformer.php
As 9188566d introduce a post transform objects event, I need for a project a pre transform objects event.
=> Dispatch an event before transforming objects

Resources/doc/cookbook/pre-transform-event.md
Changed exam_b_le to exam_p_le
=> Fixed typo in pre-transform-event.md

Resources/views/Collector/elastica.html.twig
=> [Profiler] Fix toolbar time

DependencyInjection/Compiler/RequestCompilerPass.php, FOSElasticaBundle.php, Resources/config/config.xml, Subscriber/PaginateElasticaQuerySubscriber.php
=> Make code to be compatible with Symfony 2.4+

Resources/doc/types.md
Fixed the Dynamic Templates reference, which resulted in a 404.
Also updated the Date Format reference to the new domain.
=> Fixed documentation references

CHANGELOG-3.2.md, DependencyInjection/Configuration.php, Resources/doc/cookbook/compression.md, Resources/doc/index.md, Tests/DependencyInjection/ConfigurationTest.php
Replaces https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/932
=> Add default value for new elastica "compression" param

Resources/doc/cookbook/multi-type-search.md, Resources/doc/index.md
i couldn't find this type of information in documentation, so i made one
=> docs: multi-type search

Resources/doc/cookbook/populate-events.md
Finally I've found some time to write cookbook about `Populate Events`
#744 #814
=> adding cookbook for populate events

Event/IndexPopulateEvent.php, Event/IndexResetEvent.php, Event/TransformEvent.php, Event/TypePopulateEvent.php, Event/TypeResetEvent.php
add @Event annotation for event names. see also https://github.com/symfony/symfony/commit/6857c36576b4885b88ef8b8784a7fc2551ba8962
=> add @Event annotation to let IDEs known event names and class instance

Resources/config/config.xml
Allow to configure by parameter magic _call method and throwExceptionOnInvalidIndex.
Closes #124
=> Configurable PropertyAccessor

Paginator/RawPartialResults.php
facets are now depreciated in elasticsearch 2.x
=> RawPartialResults compatibility with elastic 2.x => test for facets

Doctrine/AbstractElasticaToModelTransformer.php, Tests/DataCollector/ElasticaDataCollectorTest.php, Tests/Doctrine/AbstractElasticaToModelTransformerTest.php, Tests/Finder/TransformedFinderTest.php, Tests/Manager/RepositoryManagerTest.php, Tests/Transformer/ModelToElasticaAutoTransformerTest.php
Rebased from https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/436
=> Improve code coverage

CHANGELOG-3.2.md, Finder/PaginatedFinderInterface.php, Finder/TransformedFinder.php, Paginator/HybridPaginatorAdapter.php, Paginator/HybridPartialResults.php, Repository.php, Tests/Finder/TransformedFinderTest.php
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/507
I understand the current pagination implementation sucks, but as long as nobody is willing to rewrite pagination support, we needs this PR.
=> Pagination of hybrid results

Doctrine/AbstractElasticaToModelTransformer.php
=> Fix property access error using hydrate false option

.travis.yml
Install ES 2.x in travis builds
=> Test against ES 2

Transformer/ModelToElasticaAutoTransformer.php, Transformer/ModelToElasticaIdentifierTransformer.php
If the entity uses object that can be casted to string, the bundle should do that.
Re: @ #1156
=> Cast identifier to string in case it is an object

CHANGELOG-3.2.md, DependencyInjection/Configuration.php, DependencyInjection/FOSElasticaExtension.php, Index/Resetter.php, README.md, Resources/doc/setup.md, Resources/doc/types.md
there are some commits in 3.2 that are not in master
=> merge 3.2.x to master

DependencyInjection/Compiler/RegisterProvidersPass.php
Merge #1172 into the 3.x branch as well
=> Merge the provider priority fix into 3.x branch

composer.json
The branch alias conflicts with master.
=> [4.0] Change branch alias

CHANGELOG-4.0.md, Transformer/ModelToElasticaAutoTransformer.php
https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1182
=> Use DateTimeInterface in ModelToElasticaAutoTransformer

Index/Resetter.php
Use Interface instead of class
=> Use Interface instead of class

DependencyInjection/Configuration.php, Resources/doc/cookbook/http-auth-for-elastica.md, Resources/doc/index.md
=> Added support for username/password settings for HTTP authentication.

Resources/doc/cookbook/populate-events.md
Only a little update of the sample postPopulate trick not working with ES > V2.0
=> Post populate event fix

Transformer/ElasticaToModelTransformerCollection.php
Sending this both here and to FazlandElasticaBundle. https://github.com/fazland/FazlandElasticaBundle/pull/18
=> Fix undefined index when ignore_missing is active

Resources/doc/cookbook/populate-optimizations.md, Resources/doc/index.md
closes https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1186
=> [doc] Add cookbook on how to improve populate cmd performance

.travis.yml
currently tests on 4.x.0 branch are [broken](https://travis-ci.org/FriendsOfSymfony/FOSElasticaBundle/builds/306662234).
=> [travis] download and run desired version of ES

Resources/views/Collector/elastica.html.twig
Fixes https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1289
=> Removed non-existing framework assets

Doctrine/RepositoryManager.php
=> Remove deprecated comment in RepositoryManager.php #1275

Resources/config/propel.xml, Tests/DependencyInjection/FOSElasticaExtensionTest.php
addition to https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1240
=> Fix Propel abstract pager provider service

.travis.yml, Tests/Functional/ClientTest.php, Tests/Functional/ConfigurationManagerTest.php, Tests/Functional/IndexableCallbackTest.php, Tests/Functional/MappingToElasticaTest.php, Tests/Functional/PersistenceRepositoryTest.php, Tests/Functional/PropertyPathTest.php, Tests/Functional/SerializerTest.php, Tests/Functional/WebTestCase.php, Tests/Functional/app/AppKernel.php, Tests/Functional/app/Basic/bundles.php, Tests/Functional/app/Basic/config.yml, Tests/Functional/app/config/config.yml, composer.json
@XWB or @makasim please merge this first, then I can look into finishing #1302
=> remove unused dependencies

Command/PopulateCommand.php
fixes https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1364
=> fix options does not exist.

Resources/config/mongodb.xml, Resources/config/phpcr.xml
fixes https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1369
Should be merged to 5.x too.
=> Use correct Doctrine registry

CHANGELOG-5.0.md, src/Resources/config/config.xml
=> Fix fos_elastica.paginator.subscriber to be public

src/Event/TransformEvent.php
Types are not mixed on these variables
=> Add proper types for the TransformEvent

composer.json, src/Resources/views/Collector/elastica.html.twig, tests/Functional/ProfilerTest.php
Before:
After:
Used table sorter from the Doctrine bundle.
=> Profile panel redesign

src/Elastica/Client.php, src/Logger/ElasticaLogger.php, src/Resources/views/Collector/elastica.html.twig, tests/Functional/ProfilerTest.php, tests/Unit/Logger/ElasticaLoggerTest.php
`$data` can be either array or string https://github.com/ruflin/Elastica/blob/6.0.1/lib/Elastica/Client.php#L673
=> Array check

CHANGELOG-4.0.md
=> Remove deprecated comment in RepositoryManager.php

doc/cookbook/speed-up-populate-command-sqs.md, doc/index.md
This was never documented end-to-end with such detail before
=> Document how to use AWS SQS, with FosElasticaBundle and enqueue

src/DependencyInjection/FOSElasticaExtension.php
Just noticed this issue in the scope of #1343
=> Fix incorrect sprintf call

tests/Unit/Event/IndexEventTest.php, tests/Unit/Event/IndexPopulateEventTest.php, tests/Unit/Event/IndexResetEventTest.php, tests/Unit/Event/TransformEventTest.php, tests/Unit/Event/TypePopulateEventTest.php, tests/Unit/Event/TypeResetEventTest.php, tests/Unit/EventListener/PopulateListenerTest.php, tests/Unit/Exception/AliasIsIndexExceptionTest.php, tests/Unit/Exception/InvalidArgumentTypeExceptionTest.php
- src/Event/
- src/Exception/
- src/EventListener
=> Implement simple unit tests

tests/Unit/RepositoryTest.php
- More opinionated than previous contributions
- Relies on more recent phpunit features (withConsecutive)
=> Improve unit test coverage for Repository

src/DependencyInjection/Configuration.php
According to https://github.com/symfony/symfony/issues/20356
=> Check that element have at least one value

doc/cookbook/speed-up-populate-command.md
=> typo fixed

src/Command/PopulateCommand.php, src/Command/ResetTemplatesCommand.php
Do not prompt for confirmation if not interactive. 
New line after index refresh.
=> ResetTemplates and Populate commands improvements.

composer.json
=> Allowing ES 7.0

CHANGELOG-5.1.md, src/Finder/PaginatedFinderInterface.php, src/Finder/TransformedFinder.php, tests/Unit/Finder/TransformedFinderTest.php
This is a method I have added in one of my project. It would be nice to have it in the bundle. 
Sorry, I made this quite rapidly. What do I need to add to the PR?
=> Added a shortcut to return a pager for hybrid results

.travis.yml, composer.json, src/DependencyInjection/Configuration.php, src/DependencyInjection/FOSElasticaExtension.php, src/Doctrine/RegisterListenersService.php, src/Doctrine/RepositoryManager.php, src/Manager/RepositoryManager.php, src/Manager/RepositoryManagerInterface.php, tests/Unit/DependencyInjection/ConfigurationTest.php, tests/Unit/DependencyInjection/FOSElasticaExtensionTest.php, tests/Unit/Doctrine/MongoDBPagerProviderTest.php, tests/Unit/Doctrine/RegisterListenersServiceTest.php, tests/Unit/Doctrine/RepositoryManagerTest.php, tests/Unit/Manager/RepositoryManagerTest.php, tests/Unit/Mocks/DoctrineMongoDBCustomRepositoryMock.php
This commit has an impact on PR #1571 
@imper86 if this PR will be merged you should update naming into your PR, or if you prefer (in accord with @XWB) I can take your activity into this PR
=> Removed reference to type into repository manger classes and enabled tests with doctrine-odm

doc/cookbook/attachments.md, doc/cookbook/custom-properties.md, doc/cookbook/http-auth-for-elastica.md, doc/cookbook/logging.md, doc/cookbook/manual-provider.md, doc/cookbook/populate-events.md, doc/cookbook/pre-transform-event.md, doc/cookbook/speed-up-populate-command.md, doc/indexes.md, doc/setup.md, doc/usage.md
=> Tweak documentation

composer.json, tests/Unit/Doctrine/AbstractElasticaToModelTransformerTest.php, tests/Unit/Doctrine/ORM/ElasticaToModelTransformerTest.php, tests/Unit/Doctrine/PHPCR/ElasticaToModelTransformerTest.php, tests/Unit/Doctrine/PHPCR/ListenerTest.php, tests/Unit/Doctrine/PHPCRPagerProviderTest.php, tests/Unit/Doctrine/RegisterListenersServiceTest.php, tests/Unit/Doctrine/RepositoryManagerTest.php
Cherry picked from https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/724a3c48156eb53d2755502fc8f2ea3be9b68ca0
=> Address deprecations from persistence

composer.json, src/Message/AsyncPersistPage.php, src/Message/Handler/AsyncPersistPageHandler.php, src/Persister/AsyncPagerPersister.php, src/Resources/config/persister.xml, tests/Unit/Persister/AsyncPagerPersisterTest.php
try to continue #1622 @rimas-kudelis
=> continue - Support for queued messages via Symfony Messenger

CHANGELOG-6.0.md
=> Publish second beta version of 6.0.0

CHANGELOG-6.0.md, doc/usage.md, src/DependencyInjection/FOSElasticaExtension.php, src/Resources/config/config.xml, src/Resources/config/index.xml, tests/Functional/app/config/config.yml
@deguif Should we also make a service locator for the finder services?
=> Remove remaining public services

CHANGELOG-6.0.md, src/DependencyInjection/Configuration.php
its not released yet but this PR will cover the new param when its ready at Elastica https://github.com/ruflin/Elastica/pull/1790
=> auth_type confguration

CHANGELOG-6.0.md, src/Command/CreateCommand.php, src/Index/Resetter.php
See https://github.com/ruflin/Elastica/pull/1828
=> Fix ruflin/elastica deprecations for index creation

src/Event/PostMappingBuildEvent.php, src/Event/PostMappingBuilderEvent.php, src/Index/MappingBuilder.php, src/Resources/config/config.xml, tests/Unit/Index/MappingBuilderTest.php
Fixes https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1725
=> Add post mapping builder event

.github/workflows/continuous-integration.yaml, .gitignore, tests/Functional/app/config/config.yml
Current tests are failing as shown in https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1808
=> Fix tests for symfony 5.3

src/Doctrine/Listener.php
=> Restore defer config on terminate Listener event after persist - 6.x

doc/setup.md
enable bundle via adding it to config/bundles.php
=> Update setup.md - enable bundle via adding it to config/bundles.php

src/Command/CreateCommand.php, tests/Unit/Command/CreateCommandTest.php
Alias name should be index_name from config.
=> Fix index name for aliased index in CreateCommand

doc/usage.md
Took the workaround from https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1722#issue-726449899
=> Update usage.md regarding parsefailures

phpstan.dist.neon, src/Finder/HybridFinderInterface.php, src/Finder/PaginatedHybridFinderInterface.php, src/Finder/PaginatedRawFinderInterface.php, src/Finder/RawFinderInterface.php
Should fix the code style error introduced with https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1897
=> Fix code-style

src/Command/PopulateCommand.php, src/Event/AbstractIndexPopulateEvent.php
need to have an ability to detect current "persister"
=> added pager_persister to options for AbstractIndexPopulateEvent

composer.json, tests/Unit/Doctrine/MongoDBPagerProviderTest.php, tests/Unit/Doctrine/PHPCRPagerProviderTest.php
=> Pagerfanta v4.x compatibility

tests/Unit/Subscriber/PaginateElasticaQuerySubscriberTest.php
It was breaking tests for later PRs
=> Fix test errors related to knp-component v5.2.0
